### ISSUE TITLE
Uppercase extensions do not match when filtering movie formats

### ISSUE THREAD

**Issue by ryudice** [dev-labs-bg/swift-video-generator#10]
Honestly I'm not sure if this is the reason why it doesnt work for me but it seems if the file extension is MOV instead of mov the file gets skipped. 

I ended up writing my own code for merging since that was the only reason I wanted the library, you may want to have a look

**Comment by tgeorgieva** [comment]
I'm sorry to hear you couldn't make use of the library because of this. Thanks for bringing it up, though, I will definitely look into it.
