### ISSUE TITLE
Gif support

### ISSUE THREAD

**Issue by goreste** [dev-labs-bg/swift-video-generator#13]
Hi,

Great project. Thanks for sharing it!

i want to ask you if you've already tried to include the support to merge videos with GIFs? Especially with the gifs with a trasparent background. Because i already tried to do it but the iOS decoder doesn't support the alpha channels on videos, so when i convert a gif into a video i get the black background on the gif as result.

Just wondering if you could possibly have a solution on this.

Best and thanks again,
Paolo

**Comment by tgeorgieva** [comment]
No, I'm sorry, I haven't tried anything like that. I don't know if Apple offers such in-depth video manipulations. Transparent background videos seems like a work for a specialised video editor, not a mobile framework. But I hope you find a solution for your specifications.

Best regards, 
Teddy
