### ISSUE TITLE
Merge video with audio

### ISSUE THREAD

**Issue by abokhalel2** [dev-labs-bg/swift-video-generator#14]
Hi,
Thank you for this project, I really like it. Is there a possibility to add this feature to the project:
Merging one Video with one Audio without any images.

This can be used to:
1- Replace an audio of a certain video with a new audio.
2- Add an audio to a muted video.

I would love for this feature to be added.

**Comment by tgeorgieva** [comment]
@abokhalel2 The README file explains every functionality this project has. If it's not in the README file it can't do it.

**Comment by abokhalel2** [comment]
Thank you for your reply, I edited my post to make it as a requested feature. Thanks!

**Comment by tgeorgieva** [comment]
This has been added as a new feature in version 1.1.8.
