### ISSUE TITLE
Cannot merge a video created with .generate to other clips using .mergeMovies

### ISSUE THREAD

**Issue by kselvin** [dev-labs-bg/swift-video-generator#21]
Steps to reproduce 
1.  Create a video using a no sound and an image using .generate 

2.  Take the URL from output of above and append it to an array of video URLs.  Use .mergeMovies function on the array of URLS 

When i get the output merged video, the video created using Step 1 (from the image and no sound) does not properly merge and just shows a black screen for the duration i set using VideoGenerator.videoDurationInSeconds, the other URLS in the array show correctly though in the output merged video 

If anyone can help that would be great!  Thanks!

**Comment by tgeorgieva** [comment]
Hello.
What kind of an error are you getting?
Are you trying to merge the soundless video with other videos that do have sound? Because that is, indeed, not supported. The method merging the videos always looks for an audio track.

**Comment by kselvin** [comment]
Ah yes that must've been it.  The 1 second video I was trying to add was being created from an image with no sound.  We actually moved away from trying to do this at all, but thank you for the reply!

**Comment by kalpeshjethva18** [comment]
**VideoGenerator: Can't begin an AVAssetExportSession** I am getting this kind of error.
