### ISSUE TITLE
Modify playtime of images

### ISSUE THREAD

**Issue by ghost** [dev-labs-bg/swift-video-generator#23]
We want the generator to play the images with duration of 1 second. Which parameters do we have to change? 

When we set 'maxVideoLenght' to nofImages * 1 second, the images play 3 seconds instead and the video is cut.

**Comment by tgeorgieva** [comment]
Thank you for your interest! If you want to modify the playtime of images you'll have to change the VideoGenerator code. There is currently no public property that does what you want. You can label this as a feature request and I'll look into it.

**Comment by ghost** [comment]
@tgeorgieva could you tell me the place, where the image-duration is currently determined?

**Comment by tryWabbit** [comment]
Hey @tgeorgieva !

Thank you for this beautiful library. Are there any updates regarding this issue? I'm trying to generate a video with multiple images and no audio. I guess it's hardcoded that picture duration should be >3 per frame. 

Let me know if you can help me. 

Thanks :)
