### ISSUE TITLE
Cannot invoke initializer for type 'Range<_>' with an argument list of type '(Range<String.Index>)'

### ISSUE THREAD

**Issue by ibhavin** [dev-labs-bg/swift-video-generator#25]
While migrating to swift 4.2 there are some errors according to `Range`.

`pathString.removeSubrange(Range(pathString.startIndex..<pathString.index(pathString.startIndex, offsetBy: 7)))`

**Cannot invoke initializer for type 'Range<_>' with an argument list of type '(Range<String.Index>)'**

**Comment by tgeorgieva** [comment]
@ibhavin Pod updated to Swift 4.2.
