### ISSUE TITLE
Cannot access output video from Albums

### ISSUE THREAD

**Issue by huynq2007** [dev-labs-bg/swift-video-generator#26]
It seems that the generated videos have been saving to 
`file:///var/mobile/Containers/Data/Application/2E99B180-8C77-4853-BB21-EC0228800FE3/Documents/singleMovie.m4v`
I cannot access the output video from Albums. How can I acces the output video from Albums?

**Comment by tgeorgieva** [comment]
Hello.

The video is only being saved to the Documents folder of the app. If you want it in Albums, you'll have to write the code to move the file there.

**Comment by harshjoshi096** [comment]
Hi @huynq2007  @tgeorgieva  can anyone let me know what path do I use to save the video in album? and where do I need to change?.
Thanks
