### ISSUE TITLE
Unable to run this project in SWIFT 3

### ISSUE THREAD

**Issue by khush004** [dev-labs-bg/swift-video-generator#27]
I had Downloaded this project but I am getting Following errors 
 
![screen shot 2018-11-23 at 10 32 24 am](https://user-images.githubusercontent.com/29862624/48929065-17562380-ef0b-11e8-8032-2ac34bc7bc4f.png)

and I had also tried to install pod but I am getting Following Errors

![screen shot 2018-11-23 at 10 33 46 am](https://user-images.githubusercontent.com/29862624/48929086-466c9500-ef0b-11e8-86ef-6d66ffbac27e.png)

How can I use this project in swift 3

Please Help!
Thanks

**Comment by tgeorgieva** [comment]
@khush004 This project has never had a Swift 3 forked version. I update it as new versions of Swift come out so it's never been intended to be used by outdated versions of Swift. I don't know why you're using Swift 3 but I would highly recommend you update to the newest Swift 4.2 and Xcode 10.
