### ISSUE TITLE
MergeMultipleVideo not works

### ISSUE THREAD

**Issue by anvpn** [dev-labs-bg/swift-video-generator#28]
Hello There

Thanks for providing such a wonderful library

I am working on videoEditingApp and your library provide such a great help..:)

I want to integrate the video merge feature into my app but the code which is written in class not works , it just result me the first video

I also checked in your demo it also not work there.

Will you please check and update the code please

Thanks :)

**Comment by tgeorgieva** [comment]
@AnitaVPN I'm glad you're finding the library helpful. 
Thank you for notifying me about this bug. I'll look into it when I have time.

**Comment by anvpn** [comment]
Sure , will trying myself and if found something , will share you so you can update quickly and it helpful to others

**Comment by anvpn** [comment]
I have resolved with another way :)

**Comment by tgeorgieva** [comment]
@AnitaVPN I'm glad you found a way. I'll leave your ticket open so I can look into it when I have the time :)

**Comment by chetanPuwar21** [comment]
@AnitaVPN 
hii.... are you there?

Have you worked with audio in reverse video?
