### ISSUE TITLE
Audio quality is not too good in Reverse video(URGENT)

### ISSUE THREAD

**Issue by chetanPuwar21** [dev-labs-bg/swift-video-generator#29]
Hii... 
are you there?

When I'm trying to save reverse video with audio through your library. It was successfully saved. But audio quality is not very bad.

please help..

**Comment by tgeorgieva** [comment]
@chetanPuwar21 When I added this functionality I debated on whether to even reverse the audio and keep it. As it is, I'll probably just remove it and leave the reversal silent.

**Comment by tgeorgieva** [comment]
Audio when reversing video has been removed.
