### ISSUE TITLE
Reversing video orientation issue !!!

### ISSUE THREAD

**Issue by yoann-FM** [dev-labs-bg/swift-video-generator#30]
Hi,
I tried to build a boomerang effect.
I'm facing an issue when i reverse a captured video in portrait. The final video is stretched and wrong oriented (landscaspe instead portrait). 
Have you already made a boomerang effect ?
It's possible to implement it on you amazing class ?

Regards

**Comment by chetanPuwar21** [comment]
> Hi,
> I tried to build a boomerang effect.
> I'm facing an issue when i reverse a captured video in portrait. The final video is stretched and wrong oriented (landscaspe instead portrait).
> Have you already made a boomerang effect ?
> It's possible to implement it on you amazing class ?
> 
> Regards
Hii..  yoann
are you there?

Have you completed the task to reverse the video without orientation?

**Comment by yoann-FM** [comment]
Hi,
what do you mean by without orientation? I blocked the auto rotate and
captured in portrait mode. I tried to merge also the reversed video and
it's not working....

**Comment by yoann-FM** [comment]
Have you tested to reproduce boomerang effect of 2 sec ?

**Comment by tgeorgieva** [comment]
The orientation is now kept the same when the video is reversed.

**Comment by yoann-FM** [comment]
So it s possible to do a boomerang effect ?

**Comment by tgeorgieva** [comment]
@yoann-FM I don't know, I haven't tried. I've fixed the error with the video orientation. It's up to you to use my code and build the feature you need.
