### ISSUE TITLE
android version

### ISSUE THREAD

**Issue by bilalwarind955** [dev-labs-bg/swift-video-generator#31]
develop it for android also i am searching for android from almost two weeks but could not find any library like this for android

**Comment by tgeorgieva** [comment]
@bilalwarind955  Hello. I'm sorry that you can't find a solution for your problem. However, I'm not an Android developer and I have no intention of becoming one just to develop a solution for your problem.
Also, a word of advice - 'develop it for android' is a rude way to ask for help. Maybe explain your problem and ask for advice, article, urls or example/similar libraries next time.
