### ISSUE TITLE
This media format is not supported

### ISSUE THREAD

**Issue by lawgimenez** [dev-labs-bg/swift-video-generator#35]
When trying to merge videos in my documents directory it throws this error, both are in mp4 format.

`Error Domain=AVFoundationErrorDomain Code=-11822 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media format is not supported., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x28323e130 {Error Domain=NSOSStatusErrorDomain Code=-16976 "(null)"}}`

**Comment by tgeorgieva** [comment]
@lawgimenez Thanks for the interest in this library.

First, just printing out the error without any additional data like which line threw the error or a complete list of both videos' metadata will not garner any satisfying responses. The "mp4" videos I've used while testing all work. So there must be something different about the videos you're using. 

If the videos aren't up to the expected standards there really isn't anything I can do about it.  I'm not going to implement a video converter as well, the library is crowded enough as it is. 

My suggestion is to check over the videos and make sure they meet all Apple standards. I have an example project that has videos in it, maybe compare them to yours and see where the differences are?
