### ISSUE TITLE
Setup parameter for specific picture view duration!  

### ISSUE THREAD

**Issue by MobileAppVault** [dev-labs-bg/swift-video-generator#4]
Hi,

many thanks for this awesome code.

I was wondering if its possible to setup a specific duration between each image?

## First example:
**100 images** and I want to **generate a movie** which shows **every image for 2 seconds**.

## Second example:
**2.500 images** and I want to **generate a movie** which shows **every image for 0,2 seconds** ( in other words: 3 images per second ).

Is it possible to add a imageViewDuration param or do you have any suggestions how I can modify/ enhance the code?

Many Thanks for your help!

**Comment by MobileAppVault** [comment]
I saw you've implemented `minSingleVideoDuration` variable.

Is this the value which I need to enhance?

```
/// private property to store the minimum duration for a single video
  fileprivate var minSingleVideoDuration: Double = 3.0`
```

Many Thanks!

**Comment by tgeorgieva** [comment]
As it says, the `minSingleVideoDuration` is a property which indicates the minimum duration for a single video, not for a frame. It means that every generated video is at least 3 seconds long. 

To implement what you're saying will take some tinkering but you can look at `open func generate()` 

In the cycle `while (videoWriterInput.isReadyForMoreMediaData && frameCount < numImages)` I go through all the images and set them up as frames along with their duration based on the provided audio files. That's where you can change those settings and apply your own custom timing. 

I will look into this, although I don't think I will have time before New Years, but you can start with the function I mentioned and go from there if you need it in a hurry.

Thank you for your interest, I'm very happy to know you're finding this library useful. I will keep the issue open to add as a future customisation option.

**Comment by tgeorgieva** [comment]
@MobileAppVault You can now do this with the new **singleAudioMultipleImage** type. 

So for the first example:
You need 100 images and an audio that's **number of images * custom image duration** seconds long. 
So in this case **1** image every **2** seconds means **200** seconds audio.
