### ISSUE TITLE
Last video in array of multiple videos dicatates whether previous videos are mirrored

### ISSUE THREAD

**Issue by blurtime** [dev-labs-bg/swift-video-generator#41]
I am using an iPhone 6 (I know its quite old) with the newest iOS and the newest Swift in my Xcode and noticed something odd when I used the pod. Namely, when I recorded several videos and merged them in my project app using the URLs, the last video I added to the array invariably decided how the videos were mirrored. All of my videos are recorded in portrait orientation. I just want them to be merged the way they are, i.e. no (further) mirroring (as front camera videos are already mirrored), no change in orientation.

Here a couple of small examples of what I mean (f denotes a video recorded with the front camera, r with the rear camera): 

- [f, f, f] --> merged video stayed correctly mirrored
- [f, r, f] --> merged video stayed correctly mirrored for the f parts of the video but falsely mirrored for the r part (which shouldn't be mirrored at all and wasn't mirrored before)
- [f, f, r, f, r] --> merged video stayed correctly _un_mirrored for the r parts of the video but falsely _un_mirrored for the f parts, too (and since the f parts used to be mirrored it appears they have been "mirrored back" to unmirrored)

I guess this is somewhat related to issue #1 but thought it was quite old and it didn't seem to capture these observations so I hope it is ok that I open this issue. I love the pod so far but this has been really bugging me somehow... Is this issue already known? If not, is there a workaround? I'm not very familiar with AVFoundation but if there is no other solution, couldn't one check if the last video is "f" or "r" and adjust the other videos' mirroring accordingly? 

I would really appreciate some help! Please let me know if anything remains unclear. I'll provide as much information as I can.

**Comment by tgeorgieva** [comment]
@blurtime haven't added any code to handle changes in mirroring or orientation. Any "formatting" is done by Apple's system and AVFoundation. It's the same for the video orientation.

I don't know if AVFoundation can control the video mirroring. You will have to do research on your own and use my code as the basis for the feature. I will be happy to include any improvements you make to the library after you handle your issue. If you want to contribute, of course.

**Comment by blurtime** [comment]
@tgeorgieva I had some time on my hands and tried solving this issue again - though in vain. I created a [question on SO](https://stackoverflow.com/questions/57083151/change-preferredtransform-of-assetvideotrack-to-solve-mirroring-issue-when-mergi) yesterday but until now, nobody's answered it. There's some more information regarding my case (maybe it's a special case because the video's natural size - although portrait - seems somewhat odd(?)) and I would really appreciate if you could maybe look into it. 

EDIT: 
A couple of hours of research, comparing code and coding later, I managed to find a solution which should entirely solve this issue. I'll create a pull request very soon.

**Comment by blurtime** [comment]
The "mistake" (if you can call it that) was that when looping through the array only the last loop's orientation or rather `preferredTransform` was set equal to the one of the entire merged video, the other ones were therefore overridden if they were different (which they are when one's mirrored and the other isn't). 

I eventually didn't create a pull request but decided to post the [solution on SO](https://stackoverflow.com/questions/57083151/change-preferredtransform-of-assetvideotrack-to-solve-mirroring-issue-when-mergi/57128376#57128376) due to lack of time. I'd suggest you implement it as a new function since this function always merges the videos such that the merged video's orientation is portrait and therefore has limitations - or even better: Tweak it such that users can decide upon the wanted orientation of the merged video. Anyway, I hope I could help a little! Thank you for your pod!

**Comment by blurtime** [comment]
@tgeorgieva just edited my answer on SO again. Please check out changes made in edit 3 and 4 (from today). The quality of the merged video was a lot worse when the quality of the original videos was 1080p. Furthermore, I added the code I needed for my case which others may also be required - or not. I currently cannot explain, why it's required in my case.
