### ISSUE TITLE
This media format is not supported

### ISSUE THREAD

**Issue by derek-maurer** [dev-labs-bg/swift-video-generator#42]
Hello, I'm using the generate(withImages) func to generate a 5 second audio-less video file using an image and then using that video in a merge command. However, when attempting to use the new video generated from an image I keep getting an error saying: "Cannot Open" "This media format is not supported". However, when I pull the video file from phone I can see that it generated correctly and plays without audio just fine on my mac. Here's the code I'm using to generate the audio-less video file from the image: 

`
VideoGenerator.current.fileName = selectedStoryboardItem.name
VideoGenerator.current.maxVideoLengthInSeconds = 5
VideoGenerator.current.videoBackgroundColor = .black
VideoGenerator.current.shouldOptimiseImageForVideo = true
                    
VideoGenerator.current.generate(withImages: [image], andAudios: [], andType: .single, { (progress) in
                        
                    }, success: { (videoURL) in
                        print("finished with url: \(videoURL)")
                        print("Docs Dir: \(self.documentsDirectory())")
                        DispatchQueue.main.async {
                            selectedStoryboardItem.vidoeURL = videoURL
                            
                            self.updateStoryboardItems(with: selectedStoryboardItem)
                        }
                    }) { (error) in
                        print("Failed to generate video from image with error: \(error)")
                    }
`

And here's the code I'm using to generate the merge video: 

`
VideoGenerator.mergeMovies(videoURLs: urls, andFileName: videoName, success: { (videoURL) in
            DispatchQueue.main.async {
                loadingView.removeFromSuperview()
                
                self.player.url = videoURL
            }
        }) { (error) in
            DispatchQueue.main.async {
                loadingView.removeFromSuperview()
                print("Failed to generate video with error: \(error)")
                
                let alert = UIAlertController(title: "Oops", message: error.localizedDescription, preferredStyle: .alert)
                alert.addAction(UIAlertAction(title: "OK", style: .cancel, handler: nil))
                self.present(alert, animated: true, completion: nil)
            }
        }
`

Here's the error I'm getting from the merge func while using the video generated from an image: 

Failed to generate video with error: Error Domain=AVFoundationErrorDomain Code=-11822 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media format is not supported., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x6000004109c0 {Error Domain=NSOSStatusErrorDomain Code=-16976 "(null)"}}

**Comment by tgeorgieva** [comment]
@HomeSchoolDev Hello. Without having the videos you're using, giving me the code does about nothing, really.

You say you create a video using the merge method and then you merge that video with others? What about their video format? 

Because the error you're given is pretty straight forward.

Are you trying to merge an audio-less video with ones that have audio? The library doesn't support that.  There could be a number of things that Apple doesn't support in a video format. Check and see if all the videos you're merging conform to those standards. 

You said it yourself - "However, when I pull the video file from phone I can see that it generated correctly and plays without audio just fine on my mac." So if one of the videos is okay, maybe go over the rest and see if they conform to Apple's standards?

**Comment by derek-maurer** [comment]
So I finally figured it out and it had nothing to do with the library. AVFoundation wasn't a fan of some of the images. Some worked and some didn't. I just wrote some code to scale the images to fit into a 1080p container and it worked perfectly.

**Comment by tgeorgieva** [comment]
@HomeSchoolDev Thank you for sharing! I'm happy to hear you solved it!

**Comment by mnearents** [comment]
I am having this same issue when taking an image with the iphone camera, and merging it with audio recorded with AVAudioRecorder. Haven't gotten it to work so far.
