### ISSUE TITLE
“test.m4v” couldn’t be moved to “D10F1915-39D3-4C6F-82B5-9DCB8A4B4731” because either the former doesn’t exist, or the folder containing the latter doesn’t exist.

### ISSUE THREAD

**Issue by iOSDevGarg** [dev-labs-bg/swift-video-generator#45]
Complete Log

`file:///Users/peyman/Library/Developer/CoreSimulator/Devices/1A2CEDE0-AA2E-4E85-95AE-075162B55DA5/data/Containers/Data/Application/D10F1915-39D3-4C6F-82B5-9DCB8A4B4731/DocumentsSampleVideo1.m4v
finished
finished
“test.m4v” couldn’t be moved to “D10F1915-39D3-4C6F-82B5-9DCB8A4B4731” because either the former doesn’t exist, or the folder containing the latter doesn’t exist.
file:///Users/peyman/Library/Developer/CoreSimulator/Devices/1A2CEDE0-AA2E-4E85-95AE-075162B55DA5/data/Containers/Data/Application/D10F1915-39D3-4C6F-82B5-9DCB8A4B4731/DocumentsSampleVideo1.m4v
“test.m4v” couldn’t be moved to “D10F1915-39D3-4C6F-82B5-9DCB8A4B4731” because either the former doesn’t exist, or the folder containing the latter doesn’t exist.
file:///Users/peyman/Library/Developer/CoreSimulator/Devices/1A2CEDE0-AA2E-4E85-95AE-075162B55DA5/data/Containers/Data/Application/D10F1915-39D3-4C6F-82B5-9DCB8A4B4731/DocumentsSampleVideo1.m4v`

Any Idea why it's coming like that ?
when I use sample code provided by you that works not in my project.

I tried using pods and even adding Files manually

    //MARK: Merge Button Action
         @objc private func mergeVideoBtnAction(sender: UIButton) {
            /// Get Snapshot Image
             guard let snapShotImage = mapImgView.image else {
                return
             }
        
             /// Start Merging
             VideoGenerator.current.shouldOptimiseImageForVideo = true
             VideoGenerator.current.fileName = "SampleVideo1"
             VideoGenerator.current.generate(withImages: [#imageLiteral(resourceName: "placeholder")], andAudios: [], andType: .single, { (progress) in
            print(progress.fractionCompleted)
        }, success: { (successURL) in
            print(successURL)
        }) { (error) in
            print(error.localizedDescription)
        }
    }`

I have to use that snapshot Image to be merged as video but I used static image for now

**Comment by iOSDevGarg** [comment]
Happens in case when I don't provide audio URL there but if I provide it works well in my code whereas in your code it works even without audio file 

Second: I put my some part of required code in your sample app and got same error as mentioned
I copied entire your code just on my controller not your please suggest what can be the issue ?
if required do let me know I will send you sample code too

**Comment by tgeorgieva** [comment]
@RockinGarg What exactly are you trying to do? Your method name is "mergeVideo..." but then you're using the generate video method of the library... You say something about using a snapshot to merge with video? 

Also, you can't merge a video with sound with one without sound. The library doesn't support that case. 

I would check about some errors with your Documents path. There should be a Documents folder and the the SampleVideo1.mp4 filename. I'm not sure why that happens when you don't have audio when generating video.

`file:///Users/peyman/Library/Developer/CoreSimulator/Devices/1A2CEDE0-AA2E-4E85-95AE-075162B55DA5/data/Containers/Data/Application/D10F1915-39D3-4C6F-82B5-9DCB8A4B4731/DocumentsSampleVideo1.m4v` -> `....Application/D10F1915-39D3-4C6F-82B5-9DCB8A4B4731/Documents/SampleVideo1.m4v`

**Comment by iOSDevGarg** [comment]
Expected Output
I need to generate video from images
For now, I have one image that is "snapShotImage" its a image from Apple Maps of some location
So, I used generate video function from your code in which I passed that snapshotImage and no audio 
but it gives me that error
And in same function if I pass audio too with that single image it get converted 

My Code - https://www.dropbox.com/s/pmtel2v8ucitus8/MapSnapShot.zip?dl=0
Please check it once

Steps of my code
when you build just search for any location in search bar then it will show image from Apple maps which is actually a snapshot of location
Step 2: After image shows just click on merge button
In console you will see that error
I tried in simulator and in device too 
Same Error

**Comment by iOSDevGarg** [comment]
I tested same code in your Sample code still issue was same until I didn't provided any Audio url

**Comment by iOSDevGarg** [comment]
Hi @tgeorgieva Did you checked this issue ?

**Comment by tgeorgieva** [comment]
@RockinGarg I'm not going to be doing a code review for you. It's your responsibility to fix your code. I did fix the error with the wrong path for the saved video.  So that should'n be causing any issues anymore.

I also checked the library code - I didn't get any errors when generating a video without audio. Not a video with a single image, nor one with multiple images. Both videos generate as expected with the images I've provided. Maybe you should check how you're saving the snapshot images, what the format is?

Also, that long sequence of numbers and letters is, I assume, the simulator device Id. Maybe there is something wrong with simulator permissions?

**Comment by iOSDevGarg** [comment]
Thanks for issue fix. I haven't checked that you did commit latest code in repo 
I will check it once
yes, I agree this is my responsibility to fix my code. I was actually waiting for your code commit so I can check in my code
BTW I have tried this in simulator too and in real Device too before your latest commit

**Comment by iOSDevGarg** [comment]
did you tried providing only images and no Audio file URL 
that case let me have issue
If ii provider image and audio url both it works well

**Comment by tgeorgieva** [comment]
As I already wrote in my previous comment, I did. And it works as expected both for generating a video with a single image and multiple images and no audio.

**Comment by iOSDevGarg** [comment]
Even If I call exact button Action ```@IBAction func generateSingleVideoButtonClickHandler(_ sender: UIButton)``` from your code 
in my viewController 
Issue comes again test.mkv 

Output
Through Code in your file
```
<NSProgress: 0x600002df85a0> : Parent: 0x0 / Fraction completed: 0.5000 / Completed: 1 of 2  
<NSProgress: 0x600002df85a0> : Parent: 0x0 / Fraction completed: 1.0000 / Completed: 2 of 2  
finished
file:///Users/peyman/Library/Developer/CoreSimulator/Devices/1A2CEDE0-AA2E-4E85-95AE-075162B55DA5/data/Containers/Data/Application/AE5307BE-4BD7-451B-A171-D4395ECA9398/Documents/SampleVideo1.m4v
```

With same code in my another class
```
<NSProgress: 0x600003a75900> : Parent: 0x0 / Fraction completed: 0.5000 / Completed: 1 of 2  
<NSProgress: 0x600003a70780> : Parent: 0x0 / Fraction completed: 0.5000 / Completed: 1 of 2  
<NSProgress: 0x600003a792c0> : Parent: 0x0 / Fraction completed: 0.5000 / Completed: 1 of 2  
<NSProgress: 0x600003a75900> : Parent: 0x0 / Fraction completed: 1.0000 / Completed: 2 of 2  
<NSProgress: 0x600003a792c0> : Parent: 0x0 / Fraction completed: 1.0000 / Completed: 2 of 2  
<NSProgress: 0x600003a70780> : Parent: 0x0 / Fraction completed: 1.0000 / Completed: 2 of 2  
finished
file:///Users/peyman/Library/Developer/CoreSimulator/Devices/1A2CEDE0-AA2E-4E85-95AE-075162B55DA5/data/Containers/Data/Application/3B1BA8A1-0749-4A81-B7A4-0305AE4C24D4/Documents/SampleVideo1.m4v
finished
finished
“test.m4v” couldn’t be moved to “Documents” because either the former doesn’t exist, or the folder containing the latter doesn’t exist.
file:///Users/peyman/Library/Developer/CoreSimulator/Devices/1A2CEDE0-AA2E-4E85-95AE-075162B55DA5/data/Containers/Data/Application/3B1BA8A1-0749-4A81-B7A4-0305AE4C24D4/Documents/SampleVideo1.m4v
“test.m4v” couldn’t be moved to “Documents” because either the former doesn’t exist, or the folder containing the latter doesn’t exist.
file:///Users/peyman/Library/Developer/CoreSimulator/Devices/1A2CEDE0-AA2E-4E85-95AE-075162B55DA5/data/Containers/Data/Application/3B1BA8A1-0749-4A81-B7A4-0305AE4C24D4/Documents/SampleVideo1.m4v
```

Code in your class
```
@IBAction func generateSingleVideoButtonClickHandler(_ sender: UIButton) {
    if let audioURL4 = Bundle.main.url(forResource: Audio4 , withExtension: Mp3Extension) {
      LoadingView.lockView()
//
//      VideoGenerator.current.fileName = SingleMovieFileName
//      VideoGenerator.current.shouldOptimiseImageForVideo = true
        
        VideoGenerator.current.shouldOptimiseImageForVideo = true
        VideoGenerator.current.fileName = "SampleVideo1"
      
      VideoGenerator.current.generate(withImages: [#imageLiteral(resourceName: "image1")], andAudios: [], andType: .single, { (progress) in
        print(progress)
      }, success: { (url) in
        LoadingView.unlockView()
        print(url)
        self.createAlertView(message: self.FinishedSingleTypeVideoGeneration)
      }, failure: { (error) in
        LoadingView.unlockView()
        print(error)
        self.createAlertView(message: error.localizedDescription)
      })
    } else {
      self.createAlertView(message: MissingResourceFiles)
    }
  }
```

Code in my class
```
VideoGenerator.current.shouldOptimiseImageForVideo = true
        VideoGenerator.current.fileName = "SampleVideo1"
        VideoGenerator.current.generate(withImages: [#imageLiteral(resourceName: "image1")], andAudios: [], andType: .single, { (progress) in
            print(progress)
        }, success: { (successURL) in
            print(successURL)
        }) { (error) in
            print(error.localizedDescription)
        }
```

**Comment by iOSDevGarg** [comment]
Is there any kind of configuration you do ?
because same code is really not working in mine
I just added my classes in your example code

**Comment by tgeorgieva** [comment]
No special configuration. Just as you copied it in your comment. And it works as expected. 

The error says there is some problem with your folder management. Check that out, try some other FileManager operations and try to figure out why that happens.

**Comment by iOSDevGarg** [comment]
But just one thing that actually hits me is
Same code from your class works and same code without a single change doesn't work in my code 
in same project where your code runs

**Comment by tgeorgieva** [comment]
I'm happy you managed to reach this conclusion. Which means you're the one that needs to investigate, test and figure out why your code/device doesn't work.

**Comment by iOSDevGarg** [comment]
To reproduce same error at your end 
just create a new ViewController add a Button Action there and copy code of that merge there

**Comment by tgeorgieva** [comment]
I told you before I don't think it's my job to recreate your code and solve your issue. I've checked my code and it works as expected.

**Comment by tgeorgieva** [comment]
Last piece of advice - look over your output again. It's different from the one from my code. Try to figure out why.

**Comment by iOSDevGarg** [comment]
Well as you suggested I looked up in code of mine & yours. Thus found a really strange Observation
When I create IBAction through storyboard it works well
When I add a button Programmatically and perform same ibAction or add AddTarget then it shows Error
I hope this is not something at my end probably 
Just try if you can 
Really Thanks for such great classes

**Comment by SteliyanH** [comment]
@RockinGarg, as @tgeorgieva said all classes work well. The fact that the code works perfectly well with an IBAction and there is something wrong when adding actions programmatically points that the problem is in your code! I will evenly say where it is: 
mergeButton.addTarget(self, action: #selector(mergeVideoBtnAction(sender:)), for: .allEvents) 
The button is registered for all possible events, thus your code will fire several times which leads to the error you are describing.

Piece of advice - First read the documentation carefully (not only for the library itself but also Apple's), then analyze your code by debugging and if the error still persists then open issues.
