### ISSUE TITLE
Consider transition to Swift.Result from separate `success`, `failure` closures for modeling operations outcome.

### ISSUE THREAD

**Issue by alexey-savchenko** [dev-labs-bg/swift-video-generator#59]
The codebase now relies on old approach of using separate closures, it will be wise to update it to incorporate Swift.Result type for modeling operation outcome. 

I am willing to commit these changes and submit a pull request.

**Comment by tgeorgieva** [comment]
@alexey-savchenko Feel free to fork the project and make the changes you want. After you submit the pull request, I will look it over when I have the time and merge it if its bug free.

**Comment by tgeorgieva** [comment]
@alexey-savchenko This has been implemented in 1.4.0.
