### ISSUE TITLE
Make video from multiple image and single audio file

### ISSUE THREAD

**Issue by ibhavin** [dev-labs-bg/swift-video-generator#6]
I have made video from single image and audio file successfully and its working great.
Now I want to make video from multiple image and single audio file. Can anyone tell me solution for this?

Like from this one:
```
VideoGenerator.current.fileName = "ABC"
VideoGenerator.current.videoBackgroundColor = .black
 VideoGenerator.current.generate(withImages: [receive_Image[0], receive_Image[1], receive_Image[2]], andAudios: [song_Url], andType: .multiple, { (progress) in
            print(progress)
        }, success: { (video_url) in
            
        }) { (error) in
           
        }
```

**Comment by ibhavin** [comment]
I have made some changes in `VideoGenerator.swift`:

```
fileprivate func setup(withImages _images: [UIImage], andAudios _audios: [URL], andType _type: VideoGeneratorType) {
.
.
.
if type == .single {
      /// guard against multiple audios in single mode
      if _audios.count != 1 {
        if let _audio = _audios.first {
          audioURLs = [_audio]
        }
      }
    } else {
        if _audios.count != 1 {
            if let _audio = _audios.first {
                audioURLs = [_audio]
            }
        }
      /// guard agains more then equal audio and images for multiple
      /*if _audios.count != _images.count {
        audioURLs = Array(_audios[..._images.count])
      }*/
        
    }
.
.
.
}
```

```
open func generate(withImages _images: [UIImage], andAudios _audios: [URL], andType _type: VideoGeneratorType, _ progress: @escaping ((Progress) -> Void), success: @escaping ((URL) -> Void), failure: @escaping ((Error) -> Void)) {
.
.
.
if VideoGenerator.current.type == .single {
     // Code as it is
} else {
     /// get the right photo from the array
     imageForVideo = VideoGenerator.current.images[frameCount]

     nextStartTimeForFrame = frameCount == 0 ? CMTime(seconds: 0, preferredTimescale: 1) : CMTime(seconds: Double(elapsedTime), preferredTimescale: 1)
                
      /// add the max between the audio duration time or a minimum duration to the elapsed time
      let audio_Time = VideoGenerator.current.audioDurations[0]
      let total_Images = VideoGenerator.current.images.count
      elapsedTime += audio_Time/Double(total_Images)
      //elapsedTime += VideoGenerator.current.audioDurations[0] <= 1 ? VideoGenerator.current.minSingleVideoDuration : VideoGenerator.current.audioDurations[0]
}
.
.
.

}
```

But problem in this code is if I have 5 images and audio file length is smaller (less than 5 second) then video will not generate. It gives error `CMTimeMakeWithSeconds(0.500 seconds, timescale 1): warning: error of -0.500 introduced due to very low timescale` and in completion handler of VideoGenerator it gives error: `AVAssetWriterInputPixelBufferAdapter failed to append pixel buffer`.

If audio file length is equal or greater than images count then it will work perfect. It mean each image frame requires at least 1 second. So is there in working around if audio file is smaller than images count.

**Comment by ibhavin** [comment]
I have changed `preferredTimescale` from 1 to 600 and its working good with any length of audio file and images.

`nextStartTimeForFrame = frameCount == 0 ? CMTime(seconds: 0, preferredTimescale: 600) : CMTime(seconds: Double(elapsedTime), preferredTimescale: 600)`

**Comment by tgeorgieva** [comment]
OK, the changes are officially in the library so you can use them after you update to the latest version. Thank you for the suggestion and help. I've given you credit in the read me file next to the new feature with a link to your profile 👍 :)

**Comment by serjooo** [comment]
@tgeorgieva  I have something to add, what if I just want to make a video out of a list of images and not add audio to the video?

**Comment by serjooo** [comment]
@tgeorgieva Hello. Thanks to the existing code I was able to rewrite the code and achieve what I wanted. Here is a gist of it if you are interested in adding it to the framework. [Github Gist](https://gist.github.com/serjooo/1616957bf9afac0f862570bded93e2d1)

**Comment by tgeorgieva** [comment]
@serjooo Nice work! I will definitely check it out. 👍

**Comment by highlight0514** [comment]
Nice work!
But there is some issue.
Ex: When I use audio file that the longer than images range, the video will be display only first image.
Anyway, thanks for your efforts.
