### ISSUE TITLE
Could not build objective-c module 'SwiftVideoGenerator'

### ISSUE THREAD

**Issue by ivrylobs** [dev-labs-bg/swift-video-generator#60]
I install through pod and import the module by import SwiftVideoGenerator
while build xcode said Could not build Objective-C module 'SwiftVideoGenerator'

**Comment by ivrylobs** [comment]
i use xcode 11.2.1

**Comment by tgeorgieva** [comment]
@ivrylobs I created a new project, installed the pod, imported the framework, build and ran just fine with the latest Xcode and Swift.

Are you trying to add this library to an Objective-C project? Because this is a Swift library and if you are, then it's normal to see this error.

**Comment by ivrylobs** [comment]
> @ivrylobs I created a new project, installed the pod, imported the framework, build and ran just fine with the latest Xcode and Swift.
> 
> Are you trying to add this library to an Objective-C project? Because this is a Swift library and if you are, then it's normal to see this error.

Thanks you for the suggestion after i have converted from older version of swift and then build the project for the first time it's working fine
