### ISSUE TITLE
videoDurationInSeconds has no affect

### ISSUE THREAD

**Issue by korrolion** [dev-labs-bg/swift-video-generator#69]
Hello!

Thank you for the lib!
But I faced the problem:
If i set singleAudioMultipleImage with empty audio, the setting videoDurationInSeconds has no effect, and the video duration is 1 second.

**Comment by tgeorgieva** [comment]
Well, the property speaks for it - SINGLE AUDIO. Using that setting takes the length of the audio passed in the constructor and that becomes the video length. Without audio, the video defaults to 1 second.

**Comment by korrolion** [comment]
In my case, I have no audio and multiple Images.
It is necessary to control video duration in this case.

**Comment by tgeorgieva** [comment]
Then feel free to use my library as the base for your own solution. You can always fork the project and add new functionalities you think are vital and contribute to the project.
